name: Create and publish nightly dev Docker image

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  publish:
    name: Build, Publish
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push nightly Docker image for linux
      if: matrix.os == 'ubuntu-latest'
      run: | 
        docker build . -f Dockerfile -t smartstore/smartstore-linux:nightly
        docker push smartstore/smartstore-linux:nightly
